org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.241
loader_version_range=[1,)
geckolib_version=4.9.2

mod_id=nailong
mod_name=Nailong
mod_authors=Vermenia
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.vermenia.nailong
